# Generated by Django 4.2 on 2026-03-17 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_storeprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeprofile',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='storeprofile',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
