# Generated by Django 4.2 on 2026-03-18 07:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_adminlogin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storeprofile',
            old_name='user',
            new_name='employer',
        ),
        migrations.RenameField(
            model_name='storeprofile',
            old_name='is_verified',
            new_name='is_approved',
        ),
        migrations.RenameField(
            model_name='storeprofile',
            old_name='store_location',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='storeprofile',
            old_name='name',
            new_name='owner_name',
        ),
        migrations.AddField(
            model_name='storeprofile',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 3, 18, 6, 58, 15, 718785, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='storeprofile',
            name='category',
            field=models.CharField(default='other', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='storeprofile',
            name='description',
            field=models.TextField(default='exit'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='storeprofile',
            name='verification_document',
            field=models.FileField(upload_to='verification_docs/'),
        ),
    ]
