# Generated by Django 4.2 on 2026-03-24 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_user_storeprofile_employer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeprofile',
            name='admin_remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
