# Generated by Django 4.2 on 2026-03-28 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_timing',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
